{% set name = "XStatic" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 402544cc9e179489441054f09c807804e115ea246907de87c0355fb4f5a31268

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - xstatic

about:
  home: https://github.com/xstatic-py/xstatic
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Provide static file packages with minimal overhead.

  description: |
    The goal of XStatic family of packages is to provide static file packages with minimal overhead - without selling you some dependencies you don’t want.
  doc_url: https://xstatic.readthedocs.io/
  dev_url: https://github.com/xstatic-py/xstatic

extra:
  recipe-maintainers:
    - ReimarBauer
